### ISSUE TITLE
Error in  Exchange rate may be caused for UPDATE

### ISSUE THREAD

**Issue by luistriana28** [Vauxoo/odoo#190]
We have checked that Vauxoo/odoo is non-update with odoo/odoo, it can be a possible error with the automatic exchange rate in enterprise module.

**Comment by luistorresm** [comment]
@luistriana28 

What version?

Regards

**Comment by luistriana28** [comment]
@luistorresm 

it is in v9

**Comment by luistorresm** [comment]
Hello @luistriana28 

We generate this [PR](https://github.com/Vauxoo/odoo/pull/195), could you verify if the problem is fixed here before of the merge?

Regards

**Comment by luistriana28** [comment]
Hi @luistorresm 
The cron started to work again without any complication you can merge the [PR](https://github.com/Vauxoo/odoo/issues/190) and doesn't show any error during the update

**Comment by luistorresm** [comment]
Hi Luis, 

Could you show me in a video the difference with this PR and without this, please?

Regards

**Comment by dsabrinarg** [comment]
@maitaoriana please look for the needed commit(s) on odoo/odoo and set a PR with the cherry-pick of the change in order to solve this issue. Best regards!

**Comment by luistriana28** [comment]
This issue was fixed with the update +1
